#! /bin/sh

# Autostart
sleep .1
killall picom
picom --experimental-backend &
killall polybar
polybar -r &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

nitrogen --restore

dunst &

# Config

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config automatic_scheme alternate
bspc config border_width         2
bspc config window_gap          20

bspc config normal_border_color     "#83a598"
bspc config focused_border_color    "#d3869b"

bspc config focus_follows_pointer   true
bspc config pointer_follows_monitor true
bspc config split_ratio             0.5
bspc config borderless_monocle      true
bspc config gapless_monocle         true
