#! /bin/sh

# Autostart
autorandr --load work
sleep .1
killall picom
picom &
killall polybar
polybar -r &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
killall dunst
dunst &
killall playerctld
playerctld &

nitrogen --restore
setxkbmap -layout se

# Config

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DP-0   -d   2     5       
bspc monitor HDMI-0 -d 1   3 4       8
bspc monitor HDMI-1 -d           6 7   9

bspc config automatic_scheme alternate
bspc config border_width         2
bspc config window_gap          20

bspc config normal_border_color     "#89dceb"
bspc config focused_border_color    "#eba0ac"

bspc config focus_follows_pointer   true
bspc config pointer_follows_monitor true
bspc config split_ratio             0.5
bspc config borderless_monocle      true
bspc config gapless_monocle         true

notify-send 'Ready' 'BSPWM has initialized'


